disable taco
tue-robotics/emc_simulator pull request #38
Opened 2023-02-07 08:13 UTC by KdVos

Looks more impressive than it is, mainly because of the reformatting that happened due to for loop that was removed.

2023-02-07 09:27 UTC, MatthijsBurgh requested changes
Keep consistent naming conventions

2023-02-07 09:27 UTC, MatthijsBurgh commented on src/visualization.cpp
> +void visualize(const World& world, const Robot& robotobj, bool collision = false, bool show_full_map = false, Bbox centerframe = {-1e5, -1e5, 1e5, 1e5}, double robotRadius = 0.17)
I would still go for `robot`. People touching this code should know that class names are PascalCase and instance/argument names are snake_case.

Make this consistent. Even in this function it is all mixed.
```suggestion
void visualize(const World& world, const Robot& robot, bool collision = false, bool show_full_map = false, Bbox center_frame = {-1e5, -1e5, 1e5, 1e5}, double robot_radius = 0.17)
```

2023-02-09 08:40 UTC, KdVos commented
done

2023-02-09 09:03 UTC, MatthijsBurgh approved these changes

2023-02-09 09:04 UTC, merged